In [8]:
my_list = [1,2,3]

In [9]:
import numpy as np

In [10]:
arr = np.array(my_list)

In [11]:
arr

array([1, 2, 3])

In [12]:
my_mat = [[1,2,3], [4,5,6],[7,8,9]]

In [13]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
np.arange(0,11,2) #its is very similar to python range function

array([ 0,  2,  4,  6,  8, 10])

In [15]:
np.zeros(3)

array([0., 0., 0.])

In [16]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [17]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [18]:
#lins space return evenly space numbers over a speficied intervals
np.linspace(0,5,100)

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

In [19]:
#how to create an indentity matrix using numpy
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [20]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [21]:
np.random.rand(5)

array([0.47175966, 0.68744564, 0.28863889, 0.80898915, 0.37719614])

In [80]:
np.random.rand(5,5)

array([[0.8012783 , 0.89755718, 0.41221751, 0.53706166, 0.15859514],
       [0.76829713, 0.63933693, 0.19626824, 0.08805526, 0.3840868 ],
       [0.43265583, 0.40871455, 0.33320688, 0.41758078, 0.63246664],
       [0.97100124, 0.74615216, 0.37188829, 0.04487911, 0.90753431],
       [0.77470259, 0.03459574, 0.63840842, 0.05849417, 0.84087073]])

In [81]:
np.random.randn(4,4)

array([[ 0.37353514,  0.67302325, -1.4305081 , -0.38055391],
       [ 0.19987059,  1.85341377, -0.02523997, -1.22708739],
       [-0.64242494, -0.44163514, -0.38024288,  2.2891275 ],
       [ 0.40639922, -0.39102795,  1.25544381, -0.02280004]])

In [82]:
np.random.randint(1, 100, 10)

array([77, 38, 73, 42, 41, 96, 51, 24, 61, 77])

In [83]:
arr = np.arange(25)

In [84]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [103]:
ranarr = np.random.randint(0, 50, 10)

In [110]:
ranarr

array([24, 24, 12, 14, 16,  9, 34,  3, 23, 40])

In [111]:
#reshape method
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [112]:
ranarr.max()

40

In [113]:
ranarr.min()

3

In [117]:
ranarr.argmax()

9

In [120]:
arr = arr.reshape(5,5)

In [121]:
arr.shape 

(5, 5)

In [122]:
arr.dtype

dtype('int64')

In [123]:
from numpy.random import randint